<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>ProForm Docs {if title}- {title}{/if}</title>

    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/reset.css" />
    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/screen.css" />
    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/docs.css" />
    
    <!-- SYNTAXHIGHLIGHTER -->
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shCore.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushJScript.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushXml.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushPhp.js"></script>
    <link href="{root_url}assets/lib/syntaxhighlighter/css/shCore.css" rel="stylesheet" type="text/css" />
    <link href="{root_url}assets/lib/syntaxhighlighter/css/shThemeMidnight.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
         SyntaxHighlighter.all()
    </script>
</head>
<body>
<!-- This file was generated by the CELL build templates command. Do not modify this file directly. -->

<div class="section-content-wrapper grid-group">
    <div class="nav-global-top grid-group">&nbsp;
    </div>
    <div class="section-content-wide content-box" id="documentation">
        {if index != "yes"}
        <a href="{root_url}">&larr; ProForm Documentation Index</a>
        {/if}